export const kosovoCities = [
    "Deçan",
    "Dragash",
    "Ferizaj",
    "Fushë Kosovë",
    "Gjakovë",
    "Gjilan",
    "Gllogovc",
    "Graçanicë",
    "Hani i Elezit",
    "Istog",
    "Kaçanik",
    "Klinë",
    "Kllokot",
    "Leposaviq",
    "Lipjan",
    "Malishevë",
    "Mitrovicë",
    "Novobërdë",
    "Obiliq",
    "Partesh",
    "Pejë",
    "Podujevë",
    "Pristina",
    "Prizren",
    "Rahovec",
    "Ranillug",
    "Shtime",
    "Shtërpcë",
    "Skenderaj",
    "Suharekë",
    "Viti",
    "Vushtrri",
    "Zubin Potok",
    "Zveçan"
];


// export const kosovoCities = [
//     { id: 1, name: "Deçan" },
//     { id: 2, name: "Dragash" },
//     { id: 3, name: "Ferizaj" },
//     { id: 4, name: "Fushë Kosovë" },
//     { id: 5, name: "Gjakovë" },
//     { id: 6, name: "Gjilan" },
//     { id: 7, name: "Gllogovc" },
//     { id: 8, name: "Graçanicë" },
//     { id: 9, name: "Hani i Elezit" },
//     { id: 10, name: "Istog" },
//     { id: 11, name: "Kaçanik" },
//     { id: 12, name: "Klinë" },
//     { id: 13, name: "Kllokot" },
//     { id: 14, name: "Leposaviq" },
//     { id: 15, name: "Lipjan" },
//     { id: 16, name: "Malishevë" },
//     { id: 17, name: "Mitrovicë" },
//     { id: 18, name: "Novobërdë" },
//     { id: 19, name: "Obiliq" },
//     { id: 20, name: "Partesh" },
//     { id: 21, name: "Pejë" },
//     { id: 22, name: "Podujevë" },
//     { id: 23, name: "Pristina" },
//     { id: 24, name: "Prizren" },
//     { id: 25, name: "Rahovec" },
//     { id: 26, name: "Ranillug" },
//     { id: 27, name: "Shtime" },
//     { id: 28, name: "Shtërpcë" },
//     { id: 29, name: "Skenderaj" },
//     { id: 30, name: "Suharekë" },
//     { id: 31, name: "Viti" },
//     { id: 32, name: "Vushtrri" },
//     { id: 33, name: "Zubin Potok" },
//     { id: 34, name: "Zveçan" },
//   ];